name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@65747a0e94c86392593e40265dc539d8b276df3a
        with:
          version: v0.56.2
          path: "."

      - name: Test trivy run
        shell: bash
        run: |
          ls -ahl "."
          ls -ahl "./trivy-bin"
          ls -ahl "./trivy-bin/contrib"