name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: my-macos-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: aquasecurity/setup-trivy@v0.2.1
        with:
          version: v0.56.2
          cache: true

      - name: Test trivy run
        shell: bash
        run: trivy -v