name: Test

on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  test-macos:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: echo "Labels - ${{ toJson(github.event.pull_request.labels.*.name.d*) }}"
