name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@16199e62dc90b1dbd9e52a6564fded056acd1090
        with:
          version: v0.56.2

      - name: Test trivy run
        shell: bash
        run: trivy -v