name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@e09b21f9d465b17a0aa6d7a57e603d4b80661d37
        with:
          version: v0.56.2
          token: ${{ secrets.READ_PAT }}

      - name: Test trivy run
        shell: bash
        run: trivy -v