name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@1a5071fca2c85de4f2cbd2b5d73b42037aeaf6ef

      - name: Test trivy run
        shell: bash
        run: trivy -v