name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set platform name
        id: set-platform
        run: |
          lowercase_repo=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "PLATFORM=${lowercase_repo}" >> $GITHUB_OUTPUT

      - name: Set arch name
        id: set-arch
        run: |
          if [ "${{ runner.arch }}" == "X86" ]; then
            echo "ARCH=32bit" >> $GITHUB_OUTPUT
          elif [ "${{ runner.arch }}" == "X64" ]; then
            echo "ARCH=64bit" >> $GITHUB_OUTPUT
          elif [ "${{ runner.arch }}" == "ARM" ]; then
            echo "ARCH=ARM" >> $GITHUB_OUTPUT
          elif [ "${{ runner.arch }}" == "ARM64" ]; then
            echo "ARCH=ARM64" >> $GITHUB_OUTPUT
          else
            echo "Unsupported architecture"
            exit 1
          fi

      - name: Install trivy
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: aquasecurity/trivy
          tag: v0.56.1
          platform: ${{ steps.set-platform.outputs.PLATFROM }}
          arch: ${{ steps.set-arch.outputs.ARCH }}