name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@8864c97f0ae59376174760196d2558196a854bcb
        with:
          version: v0.56.2

      - name: Test trivy run
        shell: bash
        run: |
          ls -ahl "$HOME/.local/bin"
          ls -ahl "$HOME/.local/bin/trivy-bin"
          ls -ahl "$HOME/.local/bin/trivy-bin/contrib"