name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@a726e537949707e7f81c2938cacf3768312ccd6c
        with:
          version: v0.56.0
          cache: true

      - name: Test trivy run
        shell: bash
        run: |
          trivy -v
          ls -ahl ~
          ls -ahl ~/.local
          ls -ahl ~/.local/bin
          ls -ahl ~/.local/bin/trivy-bin