name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@2df9f605c29dbee29f7c66a8151e3b97f0874f5d
        with:
          version: v0.56.2
          token: ${{ secrets.READ_PAT }}

      - name: Test trivy run
        shell: bash
        run: trivy -v