name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@fd8c51c69200716ebc044f856bc39a67b50320d3
        with:
          version: v0.56.2

      - name: Test trivy run
        shell: bash
        run: trivy -v