name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@506cdb798d1a1c9ab2ee0b8b88cbbd7154835c4b
        with:
          version: v0.61.0

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          skip-setup-trivy: true
          exit-code: '1'
          version: v0.61.0
          cache: true
          cache-dir: .cache/trivy
