name: Test macos
on:
  workflow_dispatch:

jobs:
  test-macos:
    name: Test MacOS Python env
    runs-on: ubuntu-22.04
    steps:
      - name: Install AWS CLI
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install awscli