name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          github-server-url: "https://github.com"

      - name: Run Trivy vulnerability scanner
        uses:  aquasecurity/trivy-action@0.30.0
        with:
          image-ref: alpine
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          skip-setup-trivy: true
