name: trivy-install
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy
        uses: DmitriyLewen/setup-trivy@48e6ea900f5b2da196c9e4c0d72db5cf19964743
        with:
          version: v0.56.2

      - name: Test trivy run
        shell: bash
        run: trivy -v