name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@5be77a0a061bea7773ac7fde7f465ed4c8d365b1
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: sarif

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@5be77a0a061bea7773ac7fde7f465ed4c8d365b1
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: cyclonedx

