name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@c686e3c252f9d4a2aa5e35377c09d307d21a7386
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          version: "v0.56.1"