name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: knqyf263/trivy-action@73e12a2a4aa15d38dab23326980d3536822557e6
        env:
          TRIVY_DEBUG: true
        with:
          image-ref: 'aquasec/trivy'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: "LOW"