name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: knqyf263/trivy-action@e94275cdbe30211a51a2bdb4bba29fd45b7987cc
        env:
          TRIVY_DEBUG: true
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: 'github'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: LOW
          version: "v0.56.0"
          output: 'dependency-results.sbom.json'
          limit-severities-for-sarif: true
          github-pat: ${{ secrets.GITHUB_TOKEN }}