name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@0d9f14d79fb253616d5f38917429a6ba7c398554
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          version: "v0.56.2"
          cache: false