name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: david-marconis/trivy-action@9bd8b9689e7ae07ab1e8752e555ddf32cdfb28d0
        with:
          scan-type: 'fs'
          image-ref: '.'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: david-marconis/trivy-action@9bd8b9689e7ae07ab1e8752e555ddf32cdfb28d0
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: sarif

      - name: Run Trivy vulnerability scanner in fs mode
        uses: david-marconis/trivy-action@9bd8b9689e7ae07ab1e8752e555ddf32cdfb28d0
        with:
          scan-type: 'fs'
          image-ref: '.'