name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@abc23ab16840310ea0e532272bcd138dadfb6642
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          version: "v0.56.1"