name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DEBUG: true
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: 'github'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: LOW
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}