name: trivy-action
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@a926ff0616b6002c78ffebdcd2ffc62b7c982165
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: sarif

      - name: Run Trivy vulnerability scanner in fs mode
        uses: DmitriyLewen/trivy-action@a926ff0616b6002c78ffebdcd2ffc62b7c982165
        with:
          scan-type: 'fs'
          image-ref: '.'
          format: cyclonedx

